---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

s11:
  name: lte-s11
  interface: net1
s1u:
  name: lte-s1u
  interface: net2
s5u:
  name: lte-s5u
  interface: net3
s5c:
  name: lte-s5c
  interface: net4
sgi:
  name: lte-sgi
  interface: net5
  subnet: 10.0.1.0/24
