---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: v1
kind: Pod
metadata:
  name: http-server
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      { "name": "lte-sgi" }
    ]'
spec:
  restartPolicy: OnFailure
  containers:
  - image: python:3.8.2-alpine3.11
    name: http-server
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
    command:
      - "sh"
    args:
      - "/opt/http-server/script/init.sh"
    volumeMounts:
      - name: init-script
        mountPath: /opt/http-server/script
  volumes:
    - name: init-script
      configMap:
        name: http-server-init-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: http-server-init-script
data:
  init.sh: |
    set -o xtrace
    ip route add 10.0.3.0/24 via ${PGW_SGI_IP}
    python -m http.server 80
