---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: v1
kind: Pod
metadata:
  name: pgw
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {"name": "lte-s5u", "interface": "net1"},
        {"name": "lte-s5c", "interface": "net2"},
        {"name": "lte-sgi", "interface": "net3"}
      ]
  labels:
    app.kubernetes.io/name: pgw
    network: pdn
spec:
  initContainers:
    - name: install
      image: electrocucaracha/pgw:0.7.5
      command: ["cp", "/etc/gw-tester/pgw.yml", "/work-dir/pgw.yml"]
      volumeMounts:
        - name: config
          mountPath: /etc/gw-tester/
        - name: workdir
          mountPath: /work-dir
    - name: configure
      image: electrocucaracha/pgw:0.7.5
      command:
        - "sh"
      args:
        - "/opt/gw-tester/script/init.sh"
      volumeMounts:
        - name: init-script
          mountPath: /opt/gw-tester/script
        - name: workdir
          mountPath: /etc/gw-tester
  containers:
    - image: electrocucaracha/pgw:0.7.5
      name: pgw
      securityContext:
        capabilities:
          add: ["NET_ADMIN"]
      command: ["/opt/gw-tester/bin/pgw", "-config", "/etc/gw-tester/pgw.yml"]
      volumeMounts:
        - name: workdir
          mountPath: /etc/gw-tester
  volumes:
    - name: init-script
      configMap:
        name: pgw-init-script
    - name: workdir
      emptyDir: {}
    - name: config
      configMap:
        name: pgw-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgw-init-script
data:
  init.sh: |
    ip a
    ip route

    s5u_ip=$(ifconfig net1 | awk '/inet addr/{print substr($2,6)}')
    s5c_ip=$(ifconfig net2 | awk '/inet addr/{print substr($2,6)}')

    sed -i "s|s5c_ip:.*|s5c_ip: \"${s5c_ip}\"|g" /etc/gw-tester/pgw.yml
    sed -i "s|s5u_ip:.*|s5u_ip: \"${s5u_ip}\"|g" /etc/gw-tester/pgw.yml

    cat /etc/gw-tester/pgw.yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgw-config
data:
  pgw.yml: |
    local_addresses:
      s5c_ip: "172.25.1.14"
      s5u_ip: "172.25.0.14"
    sgi_if_name: "net3"
    route_subnet: "10.0.1.0/24"
