---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: enb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: enb
  template:
    metadata:
      labels:
        app: enb
      annotations:
        danm.k8s.io/interfaces: |
          [
            {"clusterNetwork":"lte-euu", "ip":"dynamic"},
            {"clusterNetwork":"lte-s1c", "ip":"dynamic"},
            {"clusterNetwork":"lte-s1u", "ip":"dynamic"}
          ]
    spec:
      containers:
        - image: electrocucaracha/enb
          name: enb
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          command:
            - "sh"
          args:
            - "/opt/enb/init.sh"
          volumeMounts:
            - name: init-script
              mountPath: /opt/enb
      volumes:
        - name: init-script
          configMap:
            name: enb-init-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: enb-init-script
data:
  init.sh: |
    s1c_ip=$(ifconfig eth1 | awk '/inet addr/{print substr($2,6)}')
    s1u_ip=$(ifconfig eth2 | awk '/inet addr/{print substr($2,6)}')

    sed -i "s|s1c_ip:.*|s1c_ip: \"${s1c_ip}\"|g" /etc/enb.yml
    sed -i "s|s1u_ip:.*|s1u_ip: \"${s1u_ip}\"|g" /etc/enb.yml

    /usr/local/bin/enb -config /etc/enb.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mme
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mme
  template:
    metadata:
      labels:
        app: mme
      annotations:
        danm.k8s.io/interfaces: |
          [
            {"clusterNetwork":"lte-s11", "ip":"dynamic"},
            {"clusterNetwork":"lte-s1c", "ip":"dynamic"}
          ]
    spec:
      containers:
        - image: electrocucaracha/mme
          name: mme
          command:
            - "sh"
          args:
            - "/opt/mme/init.sh"
          volumeMounts:
            - name: init-script
              mountPath: /opt/mme
      volumes:
        - name: init-script
          configMap:
            name: mme-init-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mme-init-script
data:
  init.sh: |
    s11_ip=$(ifconfig eth0 | awk '/inet addr/{print substr($2,6)}')
    s1c_ip=$(ifconfig eth1 | awk '/inet addr/{print substr($2,6)}')

    sed -i "s|s1c_addr:.*|s1c_addr: \"${s11_ip}:36412\"|g" /etc/mme.yml
    sed -i "s|s11_ip:.*|s11_ip: \"${s1c_ip}\"|g" /etc/mme.yml

    /usr/local/bin/mme -config /etc/mme.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sgw
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sgw
  template:
    metadata:
      labels:
        app: sgw
      annotations:
        danm.k8s.io/interfaces: |
          [
            {"clusterNetwork":"lte-s11", "ip":"dynamic"},
            {"clusterNetwork":"lte-s1u", "ip":"dynamic"},
            {"clusterNetwork":"lte-s5u", "ip":"dynamic"},
            {"clusterNetwork":"lte-s5c", "ip":"dynamic"}
          ]
    spec:
      containers:
        - image: electrocucaracha/sgw
          name: sgw
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          command:
            - "sh"
          args:
            - "/opt/sgw/init.sh"
          volumeMounts:
            - name: init-script
              mountPath: /opt/sgw
      volumes:
        - name: init-script
          configMap:
            name: sgw-init-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sgw-init-script
data:
  init.sh: |
    s11_ip=$(ifconfig eth0 | awk '/inet addr/{print substr($2,6)}')
    s1u_ip=$(ifconfig eth1 | awk '/inet addr/{print substr($2,6)}')
    s5c_ip=$(ifconfig eth2 | awk '/inet addr/{print substr($2,6)}')
    s5u_ip=$(ifconfig eth3 | awk '/inet addr/{print substr($2,6)}')

    sed -i "s|s11_ip:.*|s11_ip: \"${s11_ip}\"|g" /etc/sgw.yml
    sed -i "s|s1u_ip:.*|s1u_ip: \"${s1u_ip}\"|g" /etc/sgw.yml
    sed -i "s|s5c_ip:.*|s5c_ip: \"${s5c_ip}\"|g" /etc/sgw.yml
    sed -i "s|s5u_ip:.*|s5u_ip: \"${s5u_ip}\"|g" /etc/sgw.yml

    /usr/local/bin/sgw -config /etc/sgw.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgw
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pgw
  template:
    metadata:
      labels:
        app: pgw
      annotations:
        danm.k8s.io/interfaces: |
          [
            {"clusterNetwork":"lte-s5u", "ip":"dynamic"},
            {"clusterNetwork":"lte-s5c", "ip":"dynamic"},
            {"clusterNetwork":"lte-sgi", "ip":"dynamic"}
          ]
    spec:
      containers:
        - image: electrocucaracha/pgw
          name: pgw
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          command:
            - "sh"
          args:
            - "/opt/pgw/init.sh"
          volumeMounts:
            - name: init-script
              mountPath: /opt/pgw
      volumes:
        - name: init-script
          configMap:
            name: pgw-init-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgw-init-script
data:
  init.sh: |
    s5c_ip=$(ifconfig eth0 | awk '/inet addr/{print substr($2,6)}')
    s5u_ip=$(ifconfig eth1 | awk '/inet addr/{print substr($2,6)}')

    sed -i "s|s5c_ip:.*|s5c_ip: \"${s5c_ip}\"|g" /etc/pgw.yml
    sed -i "s|s5u_ip:.*|s5u_ip: \"${s5u_ip}\"|g" /etc/pgw.yml

    /usr/local/bin/pgw -config /etc/pgw.yml
