---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: danm.k8s.io/v1
kind: ClusterNetwork
metadata:
  name: lte-euu
spec:
  NetworkID: euu
  NetworkType: ipvlan
  Options:
    host_device: eth0
    vxlan: 2
    cidr: 10.0.3.0/24
    allocation_pool:
      start: 10.0.3.3
      end: 10.0.3.255
---
apiVersion: danm.k8s.io/v1
kind: ClusterNetwork
metadata:
  name: lte-sgi
spec:
  NetworkID: sgi
  NetworkType: ipvlan
  Options:
    host_device: eth0
    vxlan: 3
    cidr: 10.0.1.0/24
    allocation_pool:
      start: 10.0.1.3
      end: 10.0.1.255
---
apiVersion: danm.k8s.io/v1
kind: ClusterNetwork
metadata:
  name: lte-s1u
spec:
  NetworkID: s1u
  NetworkType: ipvlan
  Options:
    host_device: eth0
    vxlan: 4
    cidr: 172.21.0.0/24
    allocation_pool:
      start: 172.21.0.3
      end: 172.21.0.255
---
apiVersion: danm.k8s.io/v1
kind: ClusterNetwork
metadata:
  name: lte-s1c
spec:
  NetworkID: s1c
  NetworkType: ipvlan
  Options:
    host_device: eth0
    vxlan: 5
    cidr: 172.21.1.0/24
    allocation_pool:
      start: 172.21.1.3
      end: 172.21.1.255
---
apiVersion: danm.k8s.io/v1
kind: ClusterNetwork
metadata:
  name: lte-s11
spec:
  NetworkID: s11
  NetworkType: ipvlan
  Options:
    host_device: eth0
    vxlan: 6
    cidr: 172.22.0.0/24
    allocation_pool:
      start: 172.22.0.3
      end: 172.22.0.255
---
apiVersion: danm.k8s.io/v1
kind: ClusterNetwork
metadata:
  name: lte-s5u
spec:
  NetworkID: s5u
  NetworkType: ipvlan
  Options:
    host_device: eth0
    vxlan: 7
    cidr: 172.25.0.0/24
    allocation_pool:
      start: 172.25.0.3
      end: 172.25.0.255
---
apiVersion: danm.k8s.io/v1
kind: ClusterNetwork
metadata:
  name: lte-s5c
spec:
  NetworkID: s5c
  NetworkType: ipvlan
  Options:
    host_device: eth0
    vxlan: 8
    cidr: 172.25.1.0/24
    allocation_pool:
      start: 172.25.1.3
      end: 172.25.1.255
