---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

version: '2.4'

services:
  enb:
    image: electrocucaracha/enb:0.7.5
    build:
      context: ../enb
    volumes:
      - ../enb/enb_default.yml:/etc/gw-tester/enb.yml
    networks:
      lte-s1u:
        ipv4_address: 172.21.0.11
      lte-euu:
        ipv4_address: 10.0.3.254
      lte-s1c:
        ipv4_address: 172.21.1.11
    depends_on:
      - sgw
      - mme
      - pgw
    cap_add:
      - NET_ADMIN
  mme:
    image: electrocucaracha/mme:0.7.5
    build:
      context: ../mme
    volumes:
      - ../mme/mme_default.yml:/etc/gw-tester/mme.yml
    networks:
      lte-s11:
        ipv4_address: 172.22.0.12
      lte-s1c:
        ipv4_address: 172.21.1.12
  sgw:
    image: electrocucaracha/sgw:0.7.5
    build:
      context: ../sgw
    volumes:
      - ../sgw/sgw_default.yml:/etc/gw-tester/sgw.yml
    networks:
      lte-s11:
        ipv4_address: 172.22.0.13
      lte-s1u:
        ipv4_address: 172.21.0.13
      lte-s5u:
        ipv4_address: 172.25.0.13
      lte-s5c:
        ipv4_address: 172.25.1.13
    cap_add:
      - NET_ADMIN
  pgw:
    image: electrocucaracha/pgw:0.7.5
    build:
      context: ../pgw
    volumes:
      - ../pgw/pgw_default.yml:/etc/gw-tester/pgw.yml
    networks:
      lte-s5u:
        ipv4_address: 172.25.0.14
      lte-s5c:
        ipv4_address: 172.25.1.14
      lte-sgi:
        ipv4_address: 10.0.1.254
    cap_add:
      - NET_ADMIN
