---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

version: '2.4'

networks:
  lte-euu:
    driver: overlay
    driver_opts:
      com.docker.network.driver.overlay.vxlanid_list: 2
    ipam:
      driver: default
      config:
      - subnet: 10.0.3.0/24
        ip_range: 10.0.3.128/24
  lte-sgi:
    driver: overlay
    driver_opts:
      com.docker.network.driver.overlay.vxlanid_list: 3
    internal: true # This network must be internal
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24
        ip_range: 10.0.1.128/24
  lte-s1u:
    driver: overlay
    driver_opts:
      com.docker.network.driver.overlay.vxlanid_list: 4
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.21.0.0/24
        ip_range: 172.21.0.128/24
  lte-s1c:
    driver: overlay
    driver_opts:
      com.docker.network.driver.overlay.vxlanid_list: 5
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.21.1.0/24
        ip_range: 172.21.1.128/24
  lte-s11:
    driver: overlay
    driver_opts:
      com.docker.network.driver.overlay.vxlanid_list: 6
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.22.0.0/24
        ip_range: 172.22.0.128/24
  lte-s5u:
    driver: overlay
    driver_opts:
      com.docker.network.driver.overlay.vxlanid_list: 7
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.25.0.0/24
        ip_range: 172.25.0.128/24
  lte-s5c:
    driver: overlay
    driver_opts:
      com.docker.network.driver.overlay.vxlanid_list: 8
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.25.1.0/24
        ip_range: 172.25.1.128/24
