---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

kind: ConfigMap
apiVersion: v1
metadata:
  name: lte-s5u-flannel-cfg
  namespace: kube-system
data:
  cni-conf.json: |
    {
      "name": "lte-s5u",
      "cniVersion": "0.3.1",
      "subnetFile": "/run/flannel/lte-s5u.env",
      "dataDir": "/var/lib/cni/flannel_s5u",
      "delegate": {
        "bridge": "kbr6"
      }
    }
  net-conf.json: |
    {
      "Network": "172.25.0.0/24",
      "Backend": {
        "Type": "vxlan"
      }
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: etcdctl-lte-s5u
  namespace: kube-system
spec:
  template:
    spec:
      nodeSelector:
        flannel-etcd: "true"
      containers:
        - name: etcdctl-lte-s5u
          image: quay.io/coreos/etcd:v3.3.20
          env:
            - name: ETCDCTL_API
              value: "2"
          command: ["etcdctl"]
          args:
            - --no-sync
            - '--endpoint=http://$(FLANNEL_ETCD_SERVICE_HOST):12379'
            - set
            - '/s5u/network/config'
            - '{ "Network": "172.25.0.0/24", "Backend": {"Type": "vxlan", "VNI": 7}}'
      restartPolicy: Never
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lte-s5u-flannel-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: flannel
  template:
    metadata:
      labels:
        tier: node
        app: flannel
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      hostNetwork: true
      tolerations:
        - operator: Exists
          effect: NoSchedule
      serviceAccountName: flannel
      containers:
        - name: kube-flannel
          image: quay.io/coreos/flannel:v0.12.0-amd64
          command:
            - /opt/bin/flanneld
          args:
            - --ip-masq
            - -subnet-file=/run/flannel/lte-s5u.env
            - -etcd-prefix=/s5u/network
            - '-etcd-endpoints=http://$(FLANNEL_ETCD_SERVICE_HOST):12379'
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
          securityContext:
            privileged: false
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: run
              mountPath: /run/flannel
      volumes:
        - name: run
          hostPath:
            path: /run/flannel
        - name: cni
          hostPath:
            path: /etc/cni/net.d
